spring.application.name=BloodLink_api

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/bloodlink_db
spring.datasource.username=root
spring.datasource.password=tiger

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
